name: 'Section 1'
id: 's1'
groups:
  - name: 'Group 1'
    id: 'g1'
    description: | 
      Introduction of items under section 1 - group 1.
      <ul>
      <li>What</li>
      <li>Why those items</li>
      </ul>
    items:
      - question: '... question ...'
        type: 'qcm'
        id: 'i1'
        options:
          - 'option_1'
          - 'option_2'
        reviewer:
          - 'ok'
          - 'ko'
          - 'partial'
          - 'not_answered'
      - question: '... question ...'
        type: 'text'
        id: 'i2'
        placeholder: 'answer examples'
        reviewer:
          - 'ok'
          - 'ko'
          - 'partial'
          - 'not_answered/no_sense'
      - question: '... question ...'
        type: 'table_simple'
        id: 'i3'
        nb_rows: 3
        columns:
          - title: 'Column 1'
            type: 'text'
            id: 'col1'
            size: 8
            placeholder: 'Column 1 examples'
          - title: 'Column 2'
            type: 'qcm'
            id: 'col2'
            size: 4
            options:
              - 'option_a'
              - 'option_b'
              - 'option_b'
        reviewer:
          - 'ok'
          - 'ko'
          - 'partial'
          - 'not_answered/no_sense'

  - name: 'Group 2'
    id: 'g2'
    description: | 
      Introduction of items under section 1 - group 2.
      <ul>
      <li>What</li>
      <li>Why those items</li>
      </ul>
    items:
      - question: '... question ...'
        type: 'text'
        id: 'i1'
        placeholder: 'answer examples'
        reviewer:
          - 'ok'
          - 'ko'
          - 'partial'
          - 'not_answered/no_sense'
      - question: '... question ...'
        type: 'text'
        id: 'i2'
        placeholder: 'answer examples'
        reviewer:
          - 'ok'
          - 'ko'
          - 'partial'
          - 'not_answered/no_sense'

  - name: Group 3
    id: 'g3'
    description: | 
      Introduction of items under section 1 - group 3.
      <ul>
      <li>What</li>
      <li>Why those items</li>
      </ul>
    items:
      - question: '... question ...'
        type: 'qcm'
        id: 'i1'
        options:
          - 'option_1'
          - 'option_2'
        reviewer:
          - 'ok'
          - 'ko'
          - 'partial'
          - 'not_answered'
