name: Section 2
id: 's2'
groups:
  - name: Group 1
    id: 'g1'
    description: | 
      Introduction of items under section 2 - group 1.
      <ul>
      <li>What</li>
      <li>Why those items</li>
      </ul>
    items:
      - question: '... question ...'
        type: 'qcm'
        id: 'i1'
        options:
          - 'option_1'
          - 'option_2'
        reviewer:
          - 'ok'
          - 'ko'
          - 'partial'
          - 'not_answered'

  - name: Group 2
    id: 'g2'
    description: | 
      Introduction of items under section 2 - group 2.
      <ul>
      <li>What</li>
      <li>Why those items</li>
      </ul>
    items:
      - question: '... question ...'
        type: 'qcm'
        id: 'i1'
        options:
          - 'option_1'
          - 'option_2'
        reviewer:
          - 'ok'
          - 'ko'
          - 'partial'
          - 'not_answered'
