name: Section 2
id: 's2'
groups:
  - name: Group 1
    id: 'g1'
    description: | 
      <p>Introduction of items under section 2 - group 1.</p>
      <ul>
      <li>What</li>
      <li>Why those items</li>
      </ul>
    items:
      - question: '... question ...'
        type: 'qcm'
        id: 'i1'
        options:
          - 'option_1'
          - 'option_2'
        analysis:
          category: 'c1'
          priority: 'low'
        reviewer:
          - option: 'review_1'
            helper: 'if answer is option 1'
            score: 1
            status: ok
            review: 'Option 1 is suitable for ...'
            remediation: null
          - option: 'review_2'
            helper: 'if answer is option 2'
            score: 0
            status: ko
            review: 'Option 2 is not suitable for ...'
            remediation: 'Option 1 must be implemented'
          - option: 'review_3'
            helper: 'if answer is option 3'
            score: 0.5
            status: partial
            review: 'Option 3 is acceptable but not completely suitable for ...'
            remediation: 'Option 1 must be preferred'
          - option: 'not_answered'
            helper: 'if there is no answer'
            score: -0.2
            status: not_answered
            review: 'Information about X is missing'
            remediation: 'Option 1 must be implemented'

  - name: Group 2
    id: 'g2'
    description: | 
      <p>Introduction of items under section 2 - group 2.</p>
      <ul>
      <li>What</li>
      <li>Why those items</li>
      </ul>
    items:
      - question: '... question ...'
        type: 'qcm'
        id: 'i1'
        options:
          - 'option_1'
          - 'option_2'
          - 'option_3'
        analysis:
          category: 'c2'
          priority: 'low'
        reviewer:
          - option: 'review_1'
            helper: 'if answer is option 1'
            score: 1
            status: ok
            review: 'Option 1 is suitable for ...'
            remediation: null
          - option: 'review_2'
            helper: 'if answer is option 2'
            score: 0
            status: ko
            review: 'Option 2 is not suitable for ...'
            remediation: 'Option 1 must be implemented'
          - option: 'review_3'
            helper: 'if answer is option 3'
            score: 0.5
            status: partial
            review: 'Option 3 is acceptable but not completely suitable for ...'
            remediation: 'Option 1 must be preferred'
          - option: 'not_answered'
            helper: 'if there is no answer'
            score: -0.2
            status: not_answered
            review: 'Information about X is missing'
            remediation: 'Option 1 must be implemented'
