title:
  short: AQUA
  long: Auditing QUiz Application

quiz:
  version: '1.0'
  sections:
    - !include quiz.d/s1.yml
    - !include quiz.d/s2.yml
    - !include quiz.d/s3.yml

analysis:
  scoring:
    - grade: 'A'
      tag: 'strong'
      color: '#577a00'
      min: 80
      max: 100
    - grade: 'B'
      tag: 'average'
      color: '#86b300'
      min: 60
      max: 80
    - grade: 'C'
      tag: 'average'
      color: '#e6a800'
      min: 40
      max: 60
    - grade: 'D'
      tag: 'weak'
      color: '#e36b02'
      min: 20
      max: 40
    - grade: 'E'
      tag: 'weak'
      color: '#990000'
      min: 0
      max: 20

  priorities:
    - label: 'low'
      weight: 1
    - label: 'medium'
      weight: 2
    - label: 'high'
      weight: 4

  remediation_thresholds:
    score_min: 0.5
    priority_min: 'low'

  statuses:
    - label: 'ok'
      color: '#577a00'
      icon-fa: 'check-circle'
    - label: 'partial'
      color: '#e36b02'
      icon-fa: 'exclamation-triangle'
    - label: 'ko'
      color: '#990000'
      icon-fa: 'times-circle'
    - label: 'not_answered'
      color: '#363636'
      icon-fa: 'question-circle'

  summary:
    text:
      strong: 'you demonstrated a good coverage in all fields'
      average: 'you demonstrated strong foundations but some significant items  '
      weak: 'basic expectations are not met'
    priorities:
      - high
      - medium

  categories:
    - !include quiz.d/c1.yml
    - !include quiz.d/c2.yml

  docx_template: quiz.d/template.docx
