title:
  short: AQUA
  long: Auditing QUiz Application

quiz:
  version: '1.0'
  sections:
    - name: 'Section 1'
      id: 's1'
      groups:
        - name: 'Group 1'
          id: 'g1'
          description: '... Introduction for items in group 1 of section 1 ...'
          items:
            - question: '... question ...'
              type: 'qcm'
              id: 'i1'
              options:
                - 'option_1'
                - 'option_2'
              reviewer:
                - 'ok'
                - 'ko'
                - 'partial'
                - 'not_answered'
            - question: '... question ...'
              type: 'text'
              id: 'i2'
              placeholder: 'answer examples'
              reviewer:
                - 'ok'
                - 'ko'
                - 'partial'
                - 'not_answered/no_sense'
            - question: '... question ...'
              type: 'table'
              id: 'i3'
              nb_rows: 3
              columns:
                - title: 'Column 1'
                  type: 'text'
                  id: 'col1'
                  size: 8
                  placeholder: 'Column 1 examples'
                - title: 'Column 2'
                  type: 'qcm'
                  id: 'col2'
                  size: 4
                  options:
                    - 'option_a'
                    - 'option_b'
                    - 'option_b'
              reviewer:
                - 'ok'
                - 'ko'
                - 'partial'
                - 'not_answered/no_sense'

        - name: 'Group 2'
          id: 'g2'
          description: '... Introduction for items in group 2 of section 1 ...'
          items:
            - question: '... question ...'
              type: 'text'
              id: 'i1'
              placeholder: 'answer examples'
              reviewer:
                - 'ok'
                - 'ko'
                - 'partial'
                - 'not_answered/no_sense'
            - question: '... question ...'
              type: 'text'
              id: 'i2'
              placeholder: 'answer examples'
              reviewer:
                - 'ok'
                - 'ko'
                - 'partial'
                - 'not_answered/no_sense'

        - name: Group 3
          id: 'g3'
          description: ... Introduction for items in group 3 of section 1 ...
          items:
            - question: '... question ...'
              type: 'qcm'
              id: 'i1'
              options:
                - 'option_1'
                - 'option_2'
              reviewer:
                - 'ok'
                - 'ko'
                - 'partial'
                - 'not_answered'

    - name: Section 2
      id: 's2'
      groups:
        - name: Group 1
          id: 'g1'
          description: ... Introduction for items in group 1 of section 2 ...
          items:
            - question: '... question ...'
              type: 'qcm'
              id: 'i1'
              options:
                - 'option_1'
                - 'option_2'
              reviewer:
                - 'ok'
                - 'ko'
                - 'partial'
                - 'not_answered'

        - name: Group 2
          id: 'g2'
          description: ... Introduction for items in group 2 of section 2 ...
          items:
            - question: '... question ...'
              type: 'qcm'
              id: 'i1'
              options:
                - 'option_1'
                - 'option_2'
              reviewer:
                - 'ok'
                - 'ko'
                - 'partial'
                - 'not_answered'

    - name: Section 3
      id: 's3'
      groups:
        - name: Group 1
          id: 'g1'
          description: ... Introduction for items in group 1 of section 3 ...
          items:
            - question: '... question ...'
              type: 'qcm'
              id: 'i1'
              options:
                - 'option_1'
                - 'option_2'
              reviewer:
                - 'ok'
                - 'ko'
                - 'partial'
                - 'not_answered'

        - name: Group 2
          id: 'g2'
          description: ... Introduction for items in group 2 of section 3 ...
          items:
            - question: '... question ...'
              type: 'qcm'
              id: 'i1'
              options:
                - 'option_1'
                - 'option_2'
              reviewer:
                - 'ok'
                - 'ko'
                - 'partial'
                - 'not_answered'

        - name: Group 3
          id: 'g3'
          description: ... Introduction for items in group 3 of section 3 ...
          items:
            - question: '... question ...'
              type: 'qcm'
              id: 'i1'
              options:
                - 'option_1'
                - 'option_2'
              reviewer:
                - 'ok'
                - 'ko'
                - 'partial'
                - 'not_answered'
